/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/console/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/console/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/console/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/console/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConsoleSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/v1/projects/{project_uid}/origins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get: operations["listOrigins"];
        put?: never;
        post: operations["createOrigin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/origins/{origin_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                origin_uid: components["parameters"]["OriginUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteOrigin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get: operations["listApiKeys"];
        put?: never;
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/api-keys/{key_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                key_uid: components["parameters"]["KeyUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch: operations["renameApiKey"];
        trace?: never;
    };
    "/v1/projects/{project_uid}/api-keys/{key_uid}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                key_uid: components["parameters"]["KeyUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get: operations["listProjectUsers"];
        put?: never;
        post: operations["createProjectUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/users/{user_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                user_uid: components["parameters"]["UserUid"];
            };
            cookie?: never;
        };
        get: operations["getProjectUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProjectUser"];
        trace?: never;
    };
    "/v1/projects/{project_uid}/users/{user_uid}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                user_uid: components["parameters"]["UserUid"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["replaceProjectUserPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/users/{user_uid}/sessions/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                user_uid: components["parameters"]["UserUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeProjectUserSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/users/{user_uid}/passkeys/{credential_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                user_uid: components["parameters"]["UserUid"];
                credential_uid: components["parameters"]["CredentialUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePasskey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get: operations["listProjectActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTenantActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/runtime/password/authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authenticateProjectUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/runtime/passkeys/registration/options": {
        parameters: {
            query?: never;
            header: {
                "X-ComplicatedAuth-Session": components["parameters"]["ProjectSession"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["beginPasskeyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/runtime/passkeys/registration/verify": {
        parameters: {
            query?: never;
            header: {
                "X-ComplicatedAuth-Session": components["parameters"]["ProjectSession"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finishPasskeyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/runtime/passkeys/authentication/options": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["beginPasskeyAuthentication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/runtime/passkeys/authentication/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finishPasskeyAuthentication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/runtime/sessions/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["introspectProjectUserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_uid}/runtime/sessions/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeProjectUserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        Timestamp: string;
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
                request_id: string;
            };
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
            tenant_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Tenant: {
            uid: components["schemas"]["Uuid"];
            name: string;
            slug: string;
        };
        TenantMember: {
            uid: components["schemas"]["Uuid"];
            /** Format: email */
            email: string;
            display_name: string;
            /** @enum {string} */
            role: "owner";
        };
        ConsoleSession: {
            tenant: components["schemas"]["Tenant"];
            member: components["schemas"]["TenantMember"];
            expires_at: components["schemas"]["Timestamp"];
        };
        CreateProjectRequest: {
            name: string;
            /** @enum {string} */
            environment: "sandbox" | "production";
            rp_id: string;
            rp_name: string;
            /** Format: uri */
            initial_origin: string;
        };
        UpdateProjectRequest: {
            name?: string;
            /** @enum {string} */
            environment?: "sandbox" | "production";
            /** @enum {string} */
            status?: "active" | "disabled";
            rp_id?: string;
            rp_name?: string;
        };
        Project: {
            uid: components["schemas"]["Uuid"];
            name: string;
            /** @enum {string} */
            environment: "sandbox" | "production";
            /** @enum {string} */
            status: "active" | "disabled";
            rp_id: string;
            rp_name: string;
            rp_id_locked: boolean;
            origins: components["schemas"]["Origin"][];
            origin_count: number;
            user_count: number;
            api_key_count: number;
            created_at: components["schemas"]["Timestamp"];
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            next_cursor?: string | null;
        };
        CreateOriginRequest: {
            /** Format: uri */
            origin: string;
        };
        Origin: {
            uid: components["schemas"]["Uuid"];
            /** Format: uri */
            origin: string;
            created_at: components["schemas"]["Timestamp"];
        };
        NameRequest: {
            name: string;
        };
        ApiKey: {
            uid: components["schemas"]["Uuid"];
            name: string;
            prefix: string;
            /** @enum {string} */
            status: "active" | "revoked";
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
        };
        ApiKeySecret: components["schemas"]["ApiKey"] & {
            secret: string;
        };
        CreateProjectUserRequest: {
            /** Format: email */
            email: string;
            /** @default false */
            email_verified: boolean;
            password?: string;
        };
        UpdateProjectUserRequest: {
            /** Format: email */
            email?: string;
            email_verified?: boolean;
            /** @enum {string} */
            status?: "active" | "disabled";
        };
        PasswordRequest: {
            password: string;
        };
        ProjectUser: {
            uid: components["schemas"]["Uuid"];
            /** Format: email */
            email: string;
            email_verified: boolean;
            /** @enum {string} */
            status: "active" | "disabled";
            passkey_count: number;
            created_at: components["schemas"]["Timestamp"];
        };
        ProjectUserPage: {
            items: components["schemas"]["ProjectUser"][];
            next_cursor?: string | null;
        };
        RuntimePasswordRequest: components["schemas"]["LoginRequest"];
        ProjectUserSessionSecret: {
            session_reference: string;
            expires_at: components["schemas"]["Timestamp"];
            project_user: components["schemas"]["ProjectUser"];
        };
        SessionReferenceRequest: {
            session_reference: string;
        };
        ProjectUserSession: {
            active: boolean;
            expires_at: components["schemas"]["Timestamp"];
            project_user: components["schemas"]["ProjectUser"];
        };
        WebAuthnOptions: {
            ceremony_uid: components["schemas"]["Uuid"];
            public_key: {
                [key: string]: unknown;
            };
        };
        WebAuthnFinishRequest: {
            ceremony_uid: components["schemas"]["Uuid"];
            credential: {
                [key: string]: unknown;
            };
        };
        Passkey: {
            uid: components["schemas"]["Uuid"];
            created_at: components["schemas"]["Timestamp"];
        };
        AuditEvent: {
            uid: components["schemas"]["Uuid"];
            action: string;
            /** @enum {string} */
            actor_type: "tenant_member" | "project_user" | "api_key" | "system";
            /** Format: uuid */
            actor_uid?: string | null;
            target_type?: string | null;
            /** Format: uuid */
            target_uid?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
            created_at: components["schemas"]["Timestamp"];
        };
        AuditPage: {
            items: components["schemas"]["AuditEvent"][];
            next_cursor?: string | null;
        };
    };
    responses: {
        /** @description Request failed */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Origin: string;
        Cursor: string;
        Limit: number;
        ProjectUid: components["schemas"]["Uuid"];
        OriginUid: components["schemas"]["Uuid"];
        KeyUid: components["schemas"]["Uuid"];
        UserUid: components["schemas"]["Uuid"];
        CredentialUid: components["schemas"]["Uuid"];
        ProjectSession: string;
    };
    requestBodies: never;
    headers: {
        SetCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Error"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Tenant, owner, and session created */
            201: {
                headers: {
                    "Set-Cookie": components["headers"]["SetCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleSession"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SetCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleSession"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    getConsoleSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleSession"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listOrigins: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Allowed origins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Origin"][];
                    };
                };
            };
        };
    };
    createOrigin: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOriginRequest"];
            };
        };
        responses: {
            /** @description Origin created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Origin"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    deleteOrigin: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                origin_uid: components["parameters"]["OriginUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Origin deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keys without secrets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ApiKey"][];
                    };
                };
            };
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NameRequest"];
            };
        };
        responses: {
            /** @description Key and one-time secret */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeySecret"];
                };
            };
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                key_uid: components["parameters"]["KeyUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renameApiKey: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                key_uid: components["parameters"]["KeyUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NameRequest"];
            };
        };
        responses: {
            /** @description Key renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"];
                };
            };
        };
    };
    rotateApiKey: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                key_uid: components["parameters"]["KeyUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New one-time secret */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeySecret"];
                };
            };
        };
    };
    listProjectUsers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectUserPage"];
                };
            };
        };
    };
    createProjectUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectUser"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    getProjectUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                user_uid: components["parameters"]["UserUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectUser"];
                };
            };
        };
    };
    updateProjectUser: {
        parameters: {
            query?: never;
            header?: {
                Origin?: components["parameters"]["Origin"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                user_uid: components["parameters"]["UserUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectUserRequest"];
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectUser"];
                };
            };
        };
    };
    replaceProjectUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                user_uid: components["parameters"]["UserUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Password replaced and sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
        };
    };
    revokeProjectUserSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                user_uid: components["parameters"]["UserUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deletePasskey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
                user_uid: components["parameters"]["UserUid"];
                credential_uid: components["parameters"]["CredentialUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passkey removed; RP ID remains locked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProjectActivity: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
        };
    };
    listTenantActivity: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
        };
    };
    authenticateProjectUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimePasswordRequest"];
            };
        };
        responses: {
            /** @description One-time session reference */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectUserSessionSecret"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    beginPasskeyRegistration: {
        parameters: {
            query?: never;
            header: {
                "X-ComplicatedAuth-Session": components["parameters"]["ProjectSession"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ceremony and browser options */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebAuthnOptions"];
                };
            };
        };
    };
    finishPasskeyRegistration: {
        parameters: {
            query?: never;
            header: {
                "X-ComplicatedAuth-Session": components["parameters"]["ProjectSession"];
            };
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebAuthnFinishRequest"];
            };
        };
        responses: {
            /** @description Registered passkey */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Passkey"];
                };
            };
        };
    };
    beginPasskeyAuthentication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: email */
                    email?: string;
                };
            };
        };
        responses: {
            /** @description Ceremony and browser options */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebAuthnOptions"];
                };
            };
        };
    };
    finishPasskeyAuthentication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebAuthnFinishRequest"];
            };
        };
        responses: {
            /** @description One-time session reference */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectUserSessionSecret"];
                };
            };
        };
    };
    introspectProjectUserSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionReferenceRequest"];
            };
        };
        responses: {
            /** @description Active session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectUserSession"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    revokeProjectUserSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uid: components["parameters"]["ProjectUid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionReferenceRequest"];
            };
        };
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
